### ISSUE TITLE
Web Dev Tools - After 5 seconds redirecting to nullapi.html

### ISSUE THREAD

**Issue by bestmat-testing** [BestMat/bestdeveloper-issues#1]
In Web Dev Tools - After 5 seconds redirecting to **nullapi.html**, as API registered in Local Storage is null.
It must be solved using ASJSA or else will lead to a big bug.

**Comment by BestMat** [comment]
I think in Netlify right?

**Comment by bestmat-testing** [comment]
Yes, in Netlify and the old codeprojects. It must be solved before releasing the documentation.

**Comment by BestMat** [comment]
I think not necessary in **codeprojects**.

**Comment by BestMat** [comment]
Bcoz, Netlify website is in productivity.

**Comment by bestmat-testing** [comment]
But while moving ore products, it could be a **disaster**. As we have to update and run that big command in terminal millions of times.

**Comment by BestMat** [comment]
But in codeprojects, <script> tag is not supported, I think there is some update. That's why we moved from codeprojects to Glitch then to Netlify.

**Comment by bestmat-testing** [comment]
yes

**Comment by bestmat-testing** [comment]
then we could move it to Firebase Storage
