### ISSUE TITLE
Not working in Microsoft IE and Samsung Internet

### ISSUE THREAD

**Issue by enduser-bestmat** [BestMat/bestdeveloper-issues#4]
Not working in Microsoft IE and Samsung Internet. It is only supported Chrome, Edge, Firefox, Opera, Safari

**Comment by bestmat-testing** [comment]
no ne using ie now.

**Comment by bestmat-testing** [comment]
one*

**Comment by BestMat** [comment]
Use this code: ⬇

package comi.coding.prometheus.ignisai;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.webkit.WebView;
import android.webkit.WebViewClient;

public class Browser extends Activity {
    private WebView webView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Intent intent = getIntent();

        webView = (WebView) findViewById(R.id.webBrowser);
        webView.setWebViewClient(new MyWebViewClient());

        String url = "http://google.com";
        webView.getSettings().setJavaScriptEnabled(true);
        webView.loadUrl(url);
    }

    private class MyWebViewClient extends WebViewClient {
        @Override
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
            view.loadUrl(url);
            return true;
        }
    }
}

**Comment by BestMat** [comment]
now must use JSP!

**Comment by bestmat-testing** [comment]
java again? can we use kotlin?

**Comment by bestmat-testing** [comment]
is there any api for using kotlin in html?

**Comment by BestMat** [comment]
`open class Html`

**Comment by bestmat-testing** [comment]
ok.

**Comment by bestmat-testing** [comment]
i think in javascript also we can do

**Comment by bestmat-testing** [comment]
yes. use this website @enduser-bestmat , https://change-browser-bestdeveloper.netlify.app

**Comment by enduser-bestmat** [comment]
> 
> 
> now must use JSP!

now jsp, java

**Comment by enduser-bestmat** [comment]
ok. closing the issue.

**Comment by BestMat** [comment]
@enduser-bestmat and @bestmat-testing , https://change-browser-bestdeveloper.netlify.app/ is down.
@cewoh96, are you using https://change-browser-bestdeveloper.netlify.app/ ?
