### ISSUE TITLE
Github signin/signup is throwing out an error.

### ISSUE THREAD

**Issue by enduser-bestmat** [BestMat/bestdeveloper-issues#5]
Error is : **auth/account-exists-with-different-credential** :  😟
![image](https://user-images.githubusercontent.com/81220063/112112807-005b9500-8bdc-11eb-9e9c-aa8d2aab3dca.png)

**Comment by bestmat-testing** [comment]
Must be some javascript or reactjs error.

**Comment by bestmat-testing** [comment]
Github Error message:` An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address. `

Password must be wrong.

**Comment by bestmat-testing** [comment]
@bestmat-testing, try it with another account

**Comment by enduser-bestmat** [comment]
@bestmat-testing, try it with another account

**Comment by bestmat-testing** [comment]
@enduser-bestmat  try it with another account

**Comment by enduser-bestmat** [comment]
ok

**Comment by BestMat** [comment]
@bestmat-testing, check ur account settings.

**Comment by enduser-bestmat** [comment]
> 
> 
> @enduser-bestmat, check ur account settings.

ok. closing issue.
