### ISSUE TITLE
I cannot edit my file in cloud code.

### ISSUE THREAD

**Issue by cewoh96** [BestMat/bestdeveloper-issues#7]
Hi, I am using BestCloudCode, I created a file. now I want to edit it. If I go to **https://cloudcode-bestmat.netlify.app/project.html#edit-code** and then edit my file and click on the button it is not editing.

Please resolve this issue.

**Comment by BestMat** [comment]
Hello @cewoh96 , Moving to @bestmat-testing.

**Comment by BestMat** [comment]
The code is correct. huh?

**Comment by bestmat-testing** [comment]
@cewoh96 and @BestMat , are u sing FireFox?

**Comment by BestMat** [comment]
i do not sing firefox! 🤣

**Comment by bestmat-testing** [comment]
i mean using

**Comment by cewoh96** [comment]
yes i am using firefox

**Comment by bestmat-testing** [comment]
it does not work in firefox

**Comment by BestMat** [comment]
ok, i will write code for firefox with react js now.
